//
// This file is generated by generate_gcode.py and should not be edited manually!
//
// gcode_functions.h
// generated on 2017-05-17
//

#ifndef GCODE_FUNCTIONS_H
#define GCODE_FUNCTIONS_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// N_f(char *s)
// N: Line number 
int32_t N_f();

// G0_f(char *s)
// G0: Move 
int32_t G0_f();

// G1_f(char *s)
// G1: Move 
int32_t G1_f();

// G2_f(char *s)
// G2: Controlled Arc Move 
int32_t G2_f();

// G3_f(char *s)
// G3: Controlled Arc Move 
int32_t G3_f();

// G4_f(char *s)
// G4: Dwell 
int32_t G4_f();

// G6_f(char *s)
// G6: Direct Stepper Move 
int32_t G6_f();

// G10_f(char *s)
// G10: Retract 
int32_t G10_f();

// G11_f(char *s)
// G11: Unretract 
int32_t G11_f();

// G17_f(char *s)
// G17: Plane Selection (CNC specific) 
int32_t G17_f();

// G18_f(char *s)
// G18: Plane Selection (CNC specific) 
int32_t G18_f();

// G19_f(char *s)
// G19: Plane Selection (CNC specific) 
int32_t G19_f();

// G20_f(char *s)
// G20: Set Units to Inches 
int32_t G20_f();

// G21_f(char *s)
// G21: Set Units to Millimeters 
int32_t G21_f();

// G22_f(char *s)
// G22: Firmware controlled Retract/Precharge 
int32_t G22_f();

// G23_f(char *s)
// G23: Firmware controlled Retract/Precharge 
int32_t G23_f();

// G26_f(char *s)
// G26: Mesh Validation Pattern 
int32_t G26_f();

// G28_f(char *s)
// G28: Move to Origin (Home) 
int32_t G28_f();

// G29_f(char *s)
// G29: Detailed Z-Probe 
int32_t G29_f();

// G30_f(char *s)
// G30: Single Z-Probe 
int32_t G30_f();

// G31_f(char *s)
// G31: Dock Z Probe sled 
int32_t G31_f();

// G32_f(char *s)
// G32: Undock Z Probe sled 
int32_t G32_f();

// G33_f(char *s)
// G33: Firmware dependent 
int32_t G33_f();

// G38_f(char *s)
// G38: Straight Probe (CNC specific)
int32_t G38_f();

// G40_f(char *s)
// G40: Compensation Off (CNC specific) 
int32_t G40_f();

// G54_f(char *s)
// G54: Coordinate System Select (CNC specific) 
int32_t G54_f();

// G55_f(char *s)
// G55: Coordinate System Select (CNC specific)
int32_t G55_f();

// G56_f(char *s)
// G56: Coordinate System Select (CNC specific)
int32_t G56_f();

// G57_f(char *s)
// G57: Coordinate System Select (CNC specific)
int32_t G57_f();

// G58_f(char *s)
// G58: Coordinate System Select (CNC specific)
int32_t G58_f();

// G59_f(char *s)
// G59: Coordinate System Select (CNC specific) 
int32_t G59_f();

// G60_f(char *s)
// G60: save current position to slot 
int32_t G60_f();

// G61_f(char *s)
// G61: Apply/restore saved coordinates to the active extruder. 
int32_t G61_f();

// G80_f(char *s)
// G80: Cancel Canned Cycle (CNC specific) 
int32_t G80_f();

// G90_f(char *s)
// G90: Set to Absolute Positioning 
int32_t G90_f();

// G91_f(char *s)
// G91: Set to Relative Positioning 
int32_t G91_f();

// G92_f(char *s)
// G92: Set Position 
int32_t G92_f();

// G93_f(char *s)
// G93: Feed Rate Mode (Inverse Time Mode) (CNC specific) 
int32_t G93_f();

// G94_f(char *s)
// G94: Feed Rate Mode (Units per Minute) (CNC specific) 
int32_t G94_f();

// G100_f(char *s)
// G100: Calibrate floor or rod radius 
int32_t G100_f();

// G130_f(char *s)
// G130: Set digital potentiometer value 
int32_t G130_f();

// G131_f(char *s)
// G131: Remove offset 
int32_t G131_f();

// G132_f(char *s)
// G132: Calibrate endstop offsets 
int32_t G132_f();

// G133_f(char *s)
// G133: Measure steps to top 
int32_t G133_f();

// G161_f(char *s)
// G161: Home axes to minimum 
int32_t G161_f();

// G162_f(char *s)
// G162: Home axes to maximum 
int32_t G162_f();

// M0_f(char *s)
// M0: Stop or Unconditional stop 
int32_t M0_f();

// M1_f(char *s)
// M1: Sleep or Conditional stop 
int32_t M1_f();

// M2_f(char *s)
// M2: Program End 
int32_t M2_f();

// M3_f(char *s)
// M3: Spindle On, Clockwise  (CNC specific) 
int32_t M3_f();

// M4_f(char *s)
// M4: Spindle On, Counter-Clockwise (CNC specific) 
int32_t M4_f();

// M5_f(char *s)
// M5: Spindle Off (CNC specific) 
int32_t M5_f();

// M6_f(char *s)
// M6: Tool change 
int32_t M6_f();

// M7_f(char *s)
// M7: Mist Coolant On (CNC specific) 
int32_t M7_f();

// M8_f(char *s)
// M8: Flood Coolant On (CNC specific) 
int32_t M8_f();

// M9_f(char *s)
// M9: Coolant Off (CNC specific) 
int32_t M9_f();

// M10_f(char *s)
// M10: Vacuum On (CNC specific) 
int32_t M10_f();

// M11_f(char *s)
// M11: Vacuum Off (CNC specific) 
int32_t M11_f();

// M17_f(char *s)
// M17: Enable/Power all stepper motors 
int32_t M17_f();

// M18_f(char *s)
// M18: Disable all stepper motors 
int32_t M18_f();

// M20_f(char *s)
// M20: List SD card 
int32_t M20_f();

// M21_f(char *s)
// M21: Initialize SD card 
int32_t M21_f();

// M22_f(char *s)
// M22: Release SD card 
int32_t M22_f();

// M23_f(char *s)
// M23: Select SD file 
int32_t M23_f();

// M24_f(char *s)
// M24: Start/resume SD print 
int32_t M24_f();

// M25_f(char *s)
// M25: Pause SD print 
int32_t M25_f();

// M26_f(char *s)
// M26: Set SD position 
int32_t M26_f();

// M27_f(char *s)
// M27: Report SD print status 
int32_t M27_f();

// M28_f(char *s)
// M28: Begin write to SD card 
int32_t M28_f();

// M29_f(char *s)
// M29: Stop writing to SD card 
int32_t M29_f();

// M30_f(char *s)
// M30: Delete a file on the SD card or SD card start to serial 
int32_t M30_f();

// M32_f(char *s)
// M32: Select file and start SD print 
int32_t M32_f();

// M33_f(char *s)
// M33: Get the long name for an SD card file or folder 
int32_t M33_f();

// M34_f(char *s)
// M34: Set SD file sorting options 
int32_t M34_f();

// M35_f(char *s)
// M35: Upload firmware NEXTION from SD 
int32_t M35_f();

// M36_f(char *s)
// M36: Return file information 
int32_t M36_f();

// M37_f(char *s)
// M37: Simulation mode 
int32_t M37_f();

// M38_f(char *s)
// M38: Compute SHA1 hash of target file 
int32_t M38_f();

// M40_f(char *s)
// M40: Eject 
int32_t M40_f();

// M41_f(char *s)
// M41: Loop 
int32_t M41_f();

// M42_f(char *s)
// M42: Switch I/O pin 
int32_t M42_f();

// M43_f(char *s)
// M43: Pin report and debug 
int32_t M43_f();

// M48_f(char *s)
// M48: Measure Z-Probe repeatability 
int32_t M48_f();

// M70_f(char *s)
// M70: Display message 
int32_t M70_f();

// M72_f(char *s)
// M72: Play a tone or song 
int32_t M72_f();

// M73_f(char *s)
// M73: Set build percentage 
int32_t M73_f();

// M80_f(char *s)
// M80: ATX Power On 
int32_t M80_f();

// M81_f(char *s)
// M81: ATX Power Off 
int32_t M81_f();

// M82_f(char *s)
// M82: Set extruder to absolute mode 
int32_t M82_f();

// M83_f(char *s)
// M83: Set extruder to relative mode 
int32_t M83_f();

// M84_f(char *s)
// M84: Stop idle hold 
int32_t M84_f();

// M85_f(char *s)
// M85: Set inactivity shutdown timer 
int32_t M85_f();

// M92_f(char *s)
// M92: Set axis_steps_per_unit 
int32_t M92_f();

// M93_f(char *s)
// M93: Send axis_steps_per_unit 
int32_t M93_f();

// M98_f(char *s)
// M98: Get axis_hysteresis_mm 
int32_t M98_f();

// M99_f(char *s)
// M99: Set axis_hysteresis_mm 
int32_t M99_f();

// M101_f(char *s)
// M101: Turn extruder 1 on (Forward), Undo Retraction 
int32_t M101_f();

// M102_f(char *s)
// M102: Turn extruder 1 on (Reverse) 
int32_t M102_f();

// M103_f(char *s)
// M103: Turn all extruders off, Extruder Retraction 
int32_t M103_f();

// M104_f(char *s)
// M104: Set Extruder Temperature 
int32_t M104_f();

// M105_f(char *s)
// M105: Get Extruder Temperature 
int32_t M105_f();

// M106_f(char *s)
// M106: Fan On 
int32_t M106_f();

// M107_f(char *s)
// M107: Fan Off 
int32_t M107_f();

// M108_f(char *s)
// M108: Cancel Heating (Marlin) 
int32_t M108_f();

// M109_f(char *s)
// M109: Set Extruder Temperature and Wait 
int32_t M109_f();

// M110_f(char *s)
// M110: Set Current Line Number 
int32_t M110_f();

// M111_f(char *s)
// M111: Set Debug Level 
int32_t M111_f();

// M112_f(char *s)
// M112: Emergency Stop 
int32_t M112_f();

// M113_f(char *s)
// M113: Set Extruder PWM 
int32_t M113_f();

// M114_f(char *s)
// M114: Get Current Position 
int32_t M114_f();

// M115_f(char *s)
// M115: Get Firmware Version and Capabilities 
int32_t M115_f();

// M116_f(char *s)
// M116: Wait 
int32_t M116_f();

// M117_f(char *s)
// M117: Display Message 
int32_t M117_f();

// M118_f(char *s)
// M118: Negotiate Features 
int32_t M118_f();

// M119_f(char *s)
// M119: Get Endstop Status 
int32_t M119_f();

// M120_f(char *s)
// M120: Enable endstop detection 
int32_t M120_f();

// M121_f(char *s)
// M121: Disable endstop detection 
int32_t M121_f();

// M122_f(char *s)
// M122: Diagnose 
int32_t M122_f();

// M123_f(char *s)
// M123: Tachometer value 
int32_t M123_f();

// M124_f(char *s)
// M124: Immediate motor stop 
int32_t M124_f();

// M126_f(char *s)
// M126: Open Valve 
int32_t M126_f();

// M127_f(char *s)
// M127: Close Valve 
int32_t M127_f();

// M128_f(char *s)
// M128: Extruder Pressure PWM 
int32_t M128_f();

// M129_f(char *s)
// M129: Extruder pressure off 
int32_t M129_f();

// M130_f(char *s)
// M130: Set PID P value 
int32_t M130_f();

// M131_f(char *s)
// M131: Set PID I value 
int32_t M131_f();

// M132_f(char *s)
// M132: Set PID D value 
int32_t M132_f();

// M133_f(char *s)
// M133: Set PID I limit value 
int32_t M133_f();

// M134_f(char *s)
// M134: Write PID values to EEPROM 
int32_t M134_f();

// M135_f(char *s)
// M135: Set PID sample interval 
int32_t M135_f();

// M136_f(char *s)
// M136: Print PID settings to host 
int32_t M136_f();

// M140_f(char *s)
// M140: Set Bed Temperature (Fast) 
int32_t M140_f();

// M141_f(char *s)
// M141: Set Chamber Temperature (Fast) 
int32_t M141_f();

// M142_f(char *s)
// M142: Holding Pressure 
int32_t M142_f();

// M143_f(char *s)
// M143: Maximum heater temperature 
int32_t M143_f();

// M144_f(char *s)
// M144: Bed Standby 
int32_t M144_f();

// M146_f(char *s)
// M146: Set Chamber Humidity 
int32_t M146_f();

// M149_f(char *s)
// M149: Set temperature units 
int32_t M149_f();

// M150_f(char *s)
// M150: Set display color 
int32_t M150_f();

// M155_f(char *s)
// M155: Automatically send temperatures 
int32_t M155_f();

// M160_f(char *s)
// M160: Number of mixed materials 
int32_t M160_f();

// M163_f(char *s)
// M163: Set weight of mixed material 
int32_t M163_f();

// M164_f(char *s)
// M164: Store weights 
int32_t M164_f();

// M165_f(char *s)
// M165: Set multiple mix weights 
int32_t M165_f();

// M190_f(char *s)
// M190: Wait for bed temperature to reach target temp 
int32_t M190_f();

// M191_f(char *s)
// M191: Wait for chamber temperature to reach target temp 
int32_t M191_f();

// M200_f(char *s)
// M200: Set filament diameter 
int32_t M200_f();

// M201_f(char *s)
// M201: Set max printing acceleration 
int32_t M201_f();

// M202_f(char *s)
// M202: Set max travel acceleration 
int32_t M202_f();

// M203_f(char *s)
// M203: Set maximum feedrate 
int32_t M203_f();

// M204_f(char *s)
// M204: Set default acceleration 
int32_t M204_f();

// M205_f(char *s)
// M205: Advanced settings 
int32_t M205_f();

// M206_f(char *s)
// M206: Offset axes 
int32_t M206_f();

// M207_f(char *s)
// M207: Set retract length 
int32_t M207_f();

// M208_f(char *s)
// M208: Set unretract length 
int32_t M208_f();

// M209_f(char *s)
// M209: Enable automatic retract 
int32_t M209_f();

// M210_f(char *s)
// M210: Set homing feedrates 
int32_t M210_f();

// M211_f(char *s)
// M211: Disable/Enable software endstops 
int32_t M211_f();

// M212_f(char *s)
// M212: Set Bed Level Sensor Offset 
int32_t M212_f();

// M218_f(char *s)
// M218: Set Hotend Offset 
int32_t M218_f();

// M220_f(char *s)
// M220: Set speed factor override percentage 
int32_t M220_f();

// M221_f(char *s)
// M221: Set extrude factor override percentage 
int32_t M221_f();

// M222_f(char *s)
// M222: Set speed of fast XY moves 
int32_t M222_f();

// M223_f(char *s)
// M223: Set speed of fast Z moves 
int32_t M223_f();

// M224_f(char *s)
// M224: Enable extruder during fast moves 
int32_t M224_f();

// M225_f(char *s)
// M225: Disable on extruder during fast moves 
int32_t M225_f();

// M226_f(char *s)
// M226: Wait for pin state 
int32_t M226_f();

// M227_f(char *s)
// M227: Enable Automatic Reverse and Prime 
int32_t M227_f();

// M228_f(char *s)
// M228: Disable Automatic Reverse and Prime 
int32_t M228_f();

// M229_f(char *s)
// M229: Enable Automatic Reverse and Prime 
int32_t M229_f();

// M230_f(char *s)
// M230: Disable / Enable Wait for Temperature Change 
int32_t M230_f();

// M231_f(char *s)
// M231: Set OPS parameter 
int32_t M231_f();

// M232_f(char *s)
// M232: Read and reset max. advance values 
int32_t M232_f();

// M240_f(char *s)
// M240: Trigger camera 
int32_t M240_f();

// M241_f(char *s)
// M241: Stop conveyor belt motor / echo on 
int32_t M241_f();

// M245_f(char *s)
// M245: Start cooler 
int32_t M245_f();

// M246_f(char *s)
// M246: Stop cooler 
int32_t M246_f();

// M250_f(char *s)
// M250: Set LCD contrast 
int32_t M250_f();

// M251_f(char *s)
// M251: Measure Z steps from homing stop (Delta printers) 
int32_t M251_f();

// M260_f(char *s)
// M260: i2c Send Data 
int32_t M260_f();

// M261_f(char *s)
// M261: i2c Request Data 
int32_t M261_f();

// M280_f(char *s)
// M280: Set servo position 
int32_t M280_f();

// M290_f(char *s)
// M290: Baby stepping 
int32_t M290_f();

// M300_f(char *s)
// M300: Play beep sound 
int32_t M300_f();

// M301_f(char *s)
// M301: Set PID parameters 
int32_t M301_f();

// M302_f(char *s)
// M302: Allow cold extrudes 
int32_t M302_f();

// M303_f(char *s)
// M303: Run PID tuning 
int32_t M303_f();

// M304_f(char *s)
// M304: Set PID parameters - Bed 
int32_t M304_f();

// M305_f(char *s)
// M305: Set thermistor and ADC parameters 
int32_t M305_f();

// M306_f(char *s)
// M306: Set home offset calculated from toolhead position 
int32_t M306_f();

// M307_f(char *s)
// M307: Set or report heating process parameters 
int32_t M307_f();

// M320_f(char *s)
// M320: Activate autolevel (Repetier) 
int32_t M320_f();

// M321_f(char *s)
// M321: Deactivate autolevel (Repetier) 
int32_t M321_f();

// M322_f(char *s)
// M322: Reset autolevel matrix (Repetier) 
int32_t M322_f();

// M323_f(char *s)
// M323: Distortion correction on/off (Repetier) 
int32_t M323_f();

// M340_f(char *s)
// M340: Control the servos 
int32_t M340_f();

// M350_f(char *s)
// M350: Set microstepping mode 
int32_t M350_f();

// M351_f(char *s)
// M351: Toggle MS1 MS2 pins directly 
int32_t M351_f();

// M355_f(char *s)
// M355: Turn case lights on/off 
int32_t M355_f();

// M360_f(char *s)
// M360: Move to Theta 0 degree position 
int32_t M360_f();

// M361_f(char *s)
// M361: Move to Theta 90 degree position 
int32_t M361_f();

// M362_f(char *s)
// M362: Move to Psi 0 degree position 
int32_t M362_f();

// M363_f(char *s)
// M363: Move to Psi 90 degree position 
int32_t M363_f();

// M364_f(char *s)
// M364: Move to Psi + Theta 90 degree position 
int32_t M364_f();

// M365_f(char *s)
// M365: SCARA scaling factor 
int32_t M365_f();

// M366_f(char *s)
// M366: SCARA convert trim 
int32_t M366_f();

// M370_f(char *s)
// M370: Morgan manual bed level - clear map 
int32_t M370_f();

// M371_f(char *s)
// M371: Move to next calibration position 
int32_t M371_f();

// M372_f(char *s)
// M372: Record calibration value, and move to next position 
int32_t M372_f();

// M373_f(char *s)
// M373: End bed level calibration mode 
int32_t M373_f();

// M374_f(char *s)
// M374: Save calibration grid 
int32_t M374_f();

// M375_f(char *s)
// M375: Display matrix / Load Matrix 
int32_t M375_f();

// M376_f(char *s)
// M376: Set bed compensation taper 
int32_t M376_f();

// M380_f(char *s)
// M380: Activate solenoid 
int32_t M380_f();

// M381_f(char *s)
// M381: Disable all solenoids 
int32_t M381_f();

// M400_f(char *s)
// M400: Wait for current moves to finish 
int32_t M400_f();

// M401_f(char *s)
// M401: Lower z-probe 
int32_t M401_f();

// M402_f(char *s)
// M402: Raise z-probe 
int32_t M402_f();

// M404_f(char *s)
// M404: Filament width and nozzle diameter 
int32_t M404_f();

// M405_f(char *s)
// M405: Filament Sensor on 
int32_t M405_f();

// M406_f(char *s)
// M406: Filament Sensor off 
int32_t M406_f();

// M407_f(char *s)
// M407: Display filament diameter 
int32_t M407_f();

// M408_f(char *s)
// M408: Report JSON-style response 
int32_t M408_f();

// M420_f(char *s)
// M420: Leveling On/Off/Fade (Marlin) 
int32_t M420_f();

// M421_f(char *s)
// M421: Set a Mesh Bed Leveling Z coordinate 
int32_t M421_f();

// M450_f(char *s)
// M450: Report Printer Mode 
int32_t M450_f();

// M451_f(char *s)
// M451: Select FFF Printer Mode 
int32_t M451_f();

// M452_f(char *s)
// M452: Select Laser Printer Mode 
int32_t M452_f();

// M453_f(char *s)
// M453: Select CNC Printer Mode 
int32_t M453_f();

// M460_f(char *s)
// M460: Define temperature range for thermistor-controlled fan 
int32_t M460_f();

// M500_f(char *s)
// M500: Store parameters in EEPROM 
int32_t M500_f();

// M501_f(char *s)
// M501: Read parameters from EEPROM 
int32_t M501_f();

// M502_f(char *s)
// M502: Revert to the default "factory settings." 
int32_t M502_f();

// M503_f(char *s)
// M503: Print settings 
int32_t M503_f();

// M530_f(char *s)
// M530: Enable printing mode 
int32_t M530_f();

// M531_f(char *s)
// M531: Set print name 
int32_t M531_f();

// M532_f(char *s)
// M532: Set print progress 
int32_t M532_f();

// M540_f(char *s)
// M540: Enable/Disable "Stop SD Print on Endstop Hit" 
int32_t M540_f();

// M550_f(char *s)
// M550: Set Name 
int32_t M550_f();

// M551_f(char *s)
// M551: Set Password 
int32_t M551_f();

// M552_f(char *s)
// M552: Set IP address, enable/disable network interface 
int32_t M552_f();

// M553_f(char *s)
// M553: Set Netmask 
int32_t M553_f();

// M554_f(char *s)
// M554: Set Gateway 
int32_t M554_f();

// M555_f(char *s)
// M555: Set compatibility 
int32_t M555_f();

// M556_f(char *s)
// M556: Axis compensation 
int32_t M556_f();

// M557_f(char *s)
// M557: Set Z probe point or define probing grid 
int32_t M557_f();

// M558_f(char *s)
// M558: Set Z probe type 
int32_t M558_f();

// M559_f(char *s)
// M559: Upload configuration file 
int32_t M559_f();

// M560_f(char *s)
// M560: Upload web page file 
int32_t M560_f();

// M561_f(char *s)
// M561: Set Identity Transform 
int32_t M561_f();

// M562_f(char *s)
// M562: Reset temperature fault 
int32_t M562_f();

// M563_f(char *s)
// M563: Define or remove a tool 
int32_t M563_f();

// M564_f(char *s)
// M564: Limit axes 
int32_t M564_f();

// M565_f(char *s)
// M565: Set Z probe offset 
int32_t M565_f();

// M566_f(char *s)
// M566: Set allowable instantaneous speed change 
int32_t M566_f();

// M567_f(char *s)
// M567: Set tool mix ratios 
int32_t M567_f();

// M568_f(char *s)
// M568: Turn off/on tool mix ratios 
int32_t M568_f();

// M569_f(char *s)
// M569: Set axis direction and enable values 
int32_t M569_f();

// M570_f(char *s)
// M570: Configure heater fault detection 
int32_t M570_f();

// M571_f(char *s)
// M571: Set output on extrude 
int32_t M571_f();

// M572_f(char *s)
// M572: Set or report extruder pressure advance 
int32_t M572_f();

// M573_f(char *s)
// M573: Report heater PWM 
int32_t M573_f();

// M574_f(char *s)
// M574: Set endstop configuration 
int32_t M574_f();

// M575_f(char *s)
// M575: Set serial comms parameters 
int32_t M575_f();

// M577_f(char *s)
// M577: Wait until endstop is triggered 
int32_t M577_f();

// M578_f(char *s)
// M578: Fire inkjet bits 
int32_t M578_f();

// M579_f(char *s)
// M579: Scale Cartesian axes 
int32_t M579_f();

// M580_f(char *s)
// M580: Select Roland 
int32_t M580_f();

// M581_f(char *s)
// M581: Configure external trigger 
int32_t M581_f();

// M582_f(char *s)
// M582: Check external trigger 
int32_t M582_f();

// M583_f(char *s)
// M583: Wait for pin 
int32_t M583_f();

// M584_f(char *s)
// M584: Set drive mapping 
int32_t M584_f();

// M585_f(char *s)
// M585: Probe Tool 
int32_t M585_f();

// M586_f(char *s)
// M586: Configure network protocols 
int32_t M586_f();

// M587_f(char *s)
// M587: Store WiFi host network in list, or list stored networks 
int32_t M587_f();

// M588_f(char *s)
// M588: Forget WiFi host network 
int32_t M588_f();

// M589_f(char *s)
// M589: Configure access point parameters 
int32_t M589_f();

// M590_f(char *s)
// M590: Report current tool type and index 
int32_t M590_f();

// M600_f(char *s)
// M600: Filament change pause 
int32_t M600_f();

// M605_f(char *s)
// M605: Set dual x-carriage movement mode 
int32_t M605_f();

// M665_f(char *s)
// M665: Set delta configuration 
int32_t M665_f();

// M666_f(char *s)
// M666: Set delta endstop adjustment 
int32_t M666_f();

// M667_f(char *s)
// M667: Select CoreXY mode 
int32_t M667_f();

// M668_f(char *s)
// M668: Set Z-offset compensations polynomial 
int32_t M668_f();

// M669_f(char *s)
// M669: Set kinematics type and kinematics parameters 
int32_t M669_f();

// M700_f(char *s)
// M700: Level plate 
int32_t M700_f();

// M701_f(char *s)
// M701: Load filament 
int32_t M701_f();

// M702_f(char *s)
// M702: Unload filament 
int32_t M702_f();

// M703_f(char *s)
// M703: Get Board Type 
int32_t M703_f();

// M710_f(char *s)
// M710: Erase the EEPROM and reset the board 
int32_t M710_f();

// M750_f(char *s)
// M750: Enable 3D scanner extension 
int32_t M750_f();

// M751_f(char *s)
// M751: Register 3D scanner extension over USB 
int32_t M751_f();

// M752_f(char *s)
// M752: Start 3D scan 
int32_t M752_f();

// M753_f(char *s)
// M753: Cancel current 3D scanner action 
int32_t M753_f();

// M754_f(char *s)
// M754: Calibrate 3D scanner 
int32_t M754_f();

// M755_f(char *s)
// M755: Set alignment mode for 3D scanner 
int32_t M755_f();

// M756_f(char *s)
// M756: Shutdown 3D scanner 
int32_t M756_f();

// M800_f(char *s)
// M800: Fire start print procedure 
int32_t M800_f();

// M801_f(char *s)
// M801: Fire end print procedure 
int32_t M801_f();

// M851_f(char *s)
// M851: Set Z-Probe Offset 
int32_t M851_f();

// M900_f(char *s)
// M900: Set Linear Advance Scaling Factors 
int32_t M900_f();

// M905_f(char *s)
// M905: Set local date and time 
int32_t M905_f();

// M906_f(char *s)
// M906: Set motor currents 
int32_t M906_f();

// M907_f(char *s)
// M907: Set digital trimpot motor 
int32_t M907_f();

// M908_f(char *s)
// M908: Control digital trimpot directly 
int32_t M908_f();

// M909_f(char *s)
// M909: Set microstepping 
int32_t M909_f();

// M910_f(char *s)
// M910: Set decay mode 
int32_t M910_f();

// M911_f(char *s)
// M911: Set power monitor threshold voltages 
int32_t M911_f();

// M912_f(char *s)
// M912: Set electronics temperature monitor adjustment 
int32_t M912_f();

// M913_f(char *s)
// M913: Set motor percentage of normal current 
int32_t M913_f();

// M928_f(char *s)
// M928: Start SD logging 
int32_t M928_f();

// M997_f(char *s)
// M997: Perform in-application firmware update 
int32_t M997_f();

// M998_f(char *s)
// M998: Request resend of line 
int32_t M998_f();

// M999_f(char *s)
// M999: Restart after being stopped by error 
int32_t M999_f();

// G_f(char *s)
// G: List all G-codes 
int32_t G_f();

// M_f(char *s)
// M: List all M-codes 
int32_t M_f();

// T_f(char *s)
// T: Select Tool 
int32_t T_f();

#endif