//
// This file is generated by generate_gcode.py and should be copied 
// before implementing functions so it isn't overwritten!
//
// gcode_functions_template.c
// generated on 2017-07-07
//

#include "gcode_functions.h"
#include "gcode.h"

// N_f(const char *s)
// N: Line number 
int N_f(char *s) {
    debug("N_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G0_f(const char *s)
// G0: Move 
int G0_f(char *s) {
    debug("G0_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G1_f(const char *s)
// G1: Move 
int G1_f(char *s) {
    debug("G1_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G2_f(const char *s)
// G2: Controlled Arc Move 
int G2_f(char *s) {
    debug("G2_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G3_f(const char *s)
// G3: Controlled Arc Move 
int G3_f(char *s) {
    debug("G3_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G4_f(const char *s)
// G4: Dwell 
int G4_f(char *s) {
    debug("G4_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G6_f(const char *s)
// G6: Direct Stepper Move 
int G6_f(char *s) {
    debug("G6_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G10_f(const char *s)
// G10: Retract 
int G10_f(char *s) {
    debug("G10_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G11_f(const char *s)
// G11: Unretract 
int G11_f(char *s) {
    debug("G11_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G17_f(const char *s)
// G17: Plane Selection (CNC specific) 
int G17_f(char *s) {
    debug("G17_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G18_f(const char *s)
// G18: Plane Selection (CNC specific) 
int G18_f(char *s) {
    debug("G18_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G19_f(const char *s)
// G19: Plane Selection (CNC specific) 
int G19_f(char *s) {
    debug("G19_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G20_f(const char *s)
// G20: Set Units to Inches 
int G20_f(char *s) {
    debug("G20_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G21_f(const char *s)
// G21: Set Units to Millimeters 
int G21_f(char *s) {
    debug("G21_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G22_f(const char *s)
// G22: Firmware controlled Retract/Precharge 
int G22_f(char *s) {
    debug("G22_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G23_f(const char *s)
// G23: Firmware controlled Retract/Precharge 
int G23_f(char *s) {
    debug("G23_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G26_f(const char *s)
// G26: Mesh Validation Pattern 
int G26_f(char *s) {
    debug("G26_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G28_f(const char *s)
// G28: Move to Origin (Home) 
int G28_f(char *s) {
    debug("G28_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G29_f(const char *s)
// G29: Detailed Z-Probe 
int G29_f(char *s) {
    debug("G29_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G30_f(const char *s)
// G30: Single Z-Probe 
int G30_f(char *s) {
    debug("G30_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G31_f(const char *s)
// G31: Dock Z Probe sled 
int G31_f(char *s) {
    debug("G31_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G32_f(const char *s)
// G32: Undock Z Probe sled 
int G32_f(char *s) {
    debug("G32_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G33_f(const char *s)
// G33: Firmware dependent 
int G33_f(char *s) {
    debug("G33_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G38_f(const char *s)
// G38: Straight Probe (CNC specific)
int G38_f(char *s) {
    debug("G38_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G40_f(const char *s)
// G40: Compensation Off (CNC specific) 
int G40_f(char *s) {
    debug("G40_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G54_f(const char *s)
// G54: Coordinate System Select (CNC specific) 
int G54_f(char *s) {
    debug("G54_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G55_f(const char *s)
// G55: Coordinate System Select (CNC specific)
int G55_f(char *s) {
    debug("G55_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G56_f(const char *s)
// G56: Coordinate System Select (CNC specific)
int G56_f(char *s) {
    debug("G56_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G57_f(const char *s)
// G57: Coordinate System Select (CNC specific)
int G57_f(char *s) {
    debug("G57_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G58_f(const char *s)
// G58: Coordinate System Select (CNC specific)
int G58_f(char *s) {
    debug("G58_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G59_f(const char *s)
// G59: Coordinate System Select (CNC specific) 
int G59_f(char *s) {
    debug("G59_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G60_f(const char *s)
// G60: save current position to slot 
int G60_f(char *s) {
    debug("G60_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G61_f(const char *s)
// G61: Apply/restore saved coordinates to the active extruder. 
int G61_f(char *s) {
    debug("G61_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G80_f(const char *s)
// G80: Cancel Canned Cycle (CNC specific) 
int G80_f(char *s) {
    debug("G80_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G90_f(const char *s)
// G90: Set to Absolute Positioning 
int G90_f(char *s) {
    debug("G90_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G91_f(const char *s)
// G91: Set to Relative Positioning 
int G91_f(char *s) {
    debug("G91_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G92_f(const char *s)
// G92: Set Position 
int G92_f(char *s) {
    debug("G92_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G93_f(const char *s)
// G93: Feed Rate Mode (Inverse Time Mode) (CNC specific) 
int G93_f(char *s) {
    debug("G93_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G94_f(const char *s)
// G94: Feed Rate Mode (Units per Minute) (CNC specific) 
int G94_f(char *s) {
    debug("G94_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G100_f(const char *s)
// G100: Calibrate floor or rod radius 
int G100_f(char *s) {
    debug("G100_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G130_f(const char *s)
// G130: Set digital potentiometer value 
int G130_f(char *s) {
    debug("G130_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G131_f(const char *s)
// G131: Remove offset 
int G131_f(char *s) {
    debug("G131_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G132_f(const char *s)
// G132: Calibrate endstop offsets 
int G132_f(char *s) {
    debug("G132_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G133_f(const char *s)
// G133: Measure steps to top 
int G133_f(char *s) {
    debug("G133_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G161_f(const char *s)
// G161: Home axes to minimum 
int G161_f(char *s) {
    debug("G161_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G162_f(const char *s)
// G162: Home axes to maximum 
int G162_f(char *s) {
    debug("G162_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M0_f(const char *s)
// M0: Stop or Unconditional stop 
int M0_f(char *s) {
    debug("M0_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M1_f(const char *s)
// M1: Sleep or Conditional stop 
int M1_f(char *s) {
    debug("M1_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M2_f(const char *s)
// M2: Program End 
int M2_f(char *s) {
    debug("M2_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M3_f(const char *s)
// M3: Spindle On, Clockwise  (CNC specific) 
int M3_f(char *s) {
    debug("M3_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M4_f(const char *s)
// M4: Spindle On, Counter-Clockwise (CNC specific) 
int M4_f(char *s) {
    debug("M4_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M5_f(const char *s)
// M5: Spindle Off (CNC specific) 
int M5_f(char *s) {
    debug("M5_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M6_f(const char *s)
// M6: Tool change 
int M6_f(char *s) {
    debug("M6_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M7_f(const char *s)
// M7: Mist Coolant On (CNC specific) 
int M7_f(char *s) {
    debug("M7_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M8_f(const char *s)
// M8: Flood Coolant On (CNC specific) 
int M8_f(char *s) {
    debug("M8_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M9_f(const char *s)
// M9: Coolant Off (CNC specific) 
int M9_f(char *s) {
    debug("M9_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M10_f(const char *s)
// M10: Vacuum On (CNC specific) 
int M10_f(char *s) {
    debug("M10_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M11_f(const char *s)
// M11: Vacuum Off (CNC specific) 
int M11_f(char *s) {
    debug("M11_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M17_f(const char *s)
// M17: Enable/Power all stepper motors 
int M17_f(char *s) {
    debug("M17_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M18_f(const char *s)
// M18: Disable all stepper motors 
int M18_f(char *s) {
    debug("M18_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M20_f(const char *s)
// M20: List SD card 
int M20_f(char *s) {
    debug("M20_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M21_f(const char *s)
// M21: Initialize SD card 
int M21_f(char *s) {
    debug("M21_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M22_f(const char *s)
// M22: Release SD card 
int M22_f(char *s) {
    debug("M22_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M23_f(const char *s)
// M23: Select SD file 
int M23_f(char *s) {
    debug("M23_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M24_f(const char *s)
// M24: Start/resume SD print 
int M24_f(char *s) {
    debug("M24_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M25_f(const char *s)
// M25: Pause SD print 
int M25_f(char *s) {
    debug("M25_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M26_f(const char *s)
// M26: Set SD position 
int M26_f(char *s) {
    debug("M26_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M27_f(const char *s)
// M27: Report SD print status 
int M27_f(char *s) {
    debug("M27_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M28_f(const char *s)
// M28: Begin write to SD card 
int M28_f(char *s) {
    debug("M28_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M29_f(const char *s)
// M29: Stop writing to SD card 
int M29_f(char *s) {
    debug("M29_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M30_f(const char *s)
// M30: Delete a file on the SD card or SD card start to serial 
int M30_f(char *s) {
    debug("M30_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M32_f(const char *s)
// M32: Select file and start SD print 
int M32_f(char *s) {
    debug("M32_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M33_f(const char *s)
// M33: Get the long name for an SD card file or folder 
int M33_f(char *s) {
    debug("M33_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M34_f(const char *s)
// M34: Set SD file sorting options 
int M34_f(char *s) {
    debug("M34_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M35_f(const char *s)
// M35: Upload firmware NEXTION from SD 
int M35_f(char *s) {
    debug("M35_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M36_f(const char *s)
// M36: Return file information 
int M36_f(char *s) {
    debug("M36_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M37_f(const char *s)
// M37: Simulation mode 
int M37_f(char *s) {
    debug("M37_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M38_f(const char *s)
// M38: Compute SHA1 hash of target file 
int M38_f(char *s) {
    debug("M38_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M40_f(const char *s)
// M40: Eject 
int M40_f(char *s) {
    debug("M40_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M41_f(const char *s)
// M41: Loop 
int M41_f(char *s) {
    debug("M41_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M42_f(const char *s)
// M42: Switch I/O pin 
int M42_f(char *s) {
    debug("M42_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M43_f(const char *s)
// M43: Pin report and debug 
int M43_f(char *s) {
    debug("M43_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M48_f(const char *s)
// M48: Measure Z-Probe repeatability 
int M48_f(char *s) {
    debug("M48_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M70_f(const char *s)
// M70: Display message 
int M70_f(char *s) {
    debug("M70_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M72_f(const char *s)
// M72: Play a tone or song 
int M72_f(char *s) {
    debug("M72_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M73_f(const char *s)
// M73: Set build percentage 
int M73_f(char *s) {
    debug("M73_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M80_f(const char *s)
// M80: ATX Power On 
int M80_f(char *s) {
    debug("M80_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M81_f(const char *s)
// M81: ATX Power Off 
int M81_f(char *s) {
    debug("M81_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M82_f(const char *s)
// M82: Set extruder to absolute mode 
int M82_f(char *s) {
    debug("M82_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M83_f(const char *s)
// M83: Set extruder to relative mode 
int M83_f(char *s) {
    debug("M83_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M84_f(const char *s)
// M84: Stop idle hold 
int M84_f(char *s) {
    debug("M84_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M85_f(const char *s)
// M85: Set inactivity shutdown timer 
int M85_f(char *s) {
    debug("M85_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M92_f(const char *s)
// M92: Set axis_steps_per_unit 
int M92_f(char *s) {
    debug("M92_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M93_f(const char *s)
// M93: Send axis_steps_per_unit 
int M93_f(char *s) {
    debug("M93_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M98_f(const char *s)
// M98: Get axis_hysteresis_mm 
int M98_f(char *s) {
    debug("M98_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M99_f(const char *s)
// M99: Set axis_hysteresis_mm 
int M99_f(char *s) {
    debug("M99_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M101_f(const char *s)
// M101: Turn extruder 1 on (Forward), Undo Retraction 
int M101_f(char *s) {
    debug("M101_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M102_f(const char *s)
// M102: Turn extruder 1 on (Reverse) 
int M102_f(char *s) {
    debug("M102_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M103_f(const char *s)
// M103: Turn all extruders off, Extruder Retraction 
int M103_f(char *s) {
    debug("M103_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M104_f(const char *s)
// M104: Set Extruder Temperature 
int M104_f(char *s) {
    debug("M104_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M105_f(const char *s)
// M105: Get Extruder Temperature 
int M105_f(char *s) {
    debug("M105_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M106_f(const char *s)
// M106: Fan On 
int M106_f(char *s) {
    debug("M106_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M107_f(const char *s)
// M107: Fan Off 
int M107_f(char *s) {
    debug("M107_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M108_f(const char *s)
// M108: Cancel Heating (Marlin) 
int M108_f(char *s) {
    debug("M108_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M109_f(const char *s)
// M109: Set Extruder Temperature and Wait 
int M109_f(char *s) {
    debug("M109_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M110_f(const char *s)
// M110: Set Current Line Number 
int M110_f(char *s) {
    debug("M110_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M111_f(const char *s)
// M111: Set Debug Level 
int M111_f(char *s) {
    debug("M111_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M112_f(const char *s)
// M112: Emergency Stop 
int M112_f(char *s) {
    debug("M112_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M113_f(const char *s)
// M113: Set Extruder PWM 
int M113_f(char *s) {
    debug("M113_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M114_f(const char *s)
// M114: Get Current Position 
int M114_f(char *s) {
    debug("M114_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M115_f(const char *s)
// M115: Get Firmware Version and Capabilities 
int M115_f(char *s) {
    debug("M115_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M116_f(const char *s)
// M116: Wait 
int M116_f(char *s) {
    debug("M116_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M117_f(const char *s)
// M117: Display Message 
int M117_f(char *s) {
    debug("M117_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M118_f(const char *s)
// M118: Negotiate Features 
int M118_f(char *s) {
    debug("M118_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M119_f(const char *s)
// M119: Get Endstop Status 
int M119_f(char *s) {
    debug("M119_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M120_f(const char *s)
// M120: Enable endstop detection 
int M120_f(char *s) {
    debug("M120_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M121_f(const char *s)
// M121: Disable endstop detection 
int M121_f(char *s) {
    debug("M121_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M122_f(const char *s)
// M122: Diagnose 
int M122_f(char *s) {
    debug("M122_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M123_f(const char *s)
// M123: Tachometer value 
int M123_f(char *s) {
    debug("M123_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M124_f(const char *s)
// M124: Immediate motor stop 
int M124_f(char *s) {
    debug("M124_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M126_f(const char *s)
// M126: Open Valve 
int M126_f(char *s) {
    debug("M126_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M127_f(const char *s)
// M127: Close Valve 
int M127_f(char *s) {
    debug("M127_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M128_f(const char *s)
// M128: Extruder Pressure PWM 
int M128_f(char *s) {
    debug("M128_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M129_f(const char *s)
// M129: Extruder pressure off 
int M129_f(char *s) {
    debug("M129_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M130_f(const char *s)
// M130: Set PID P value 
int M130_f(char *s) {
    debug("M130_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M131_f(const char *s)
// M131: Set PID I value 
int M131_f(char *s) {
    debug("M131_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M132_f(const char *s)
// M132: Set PID D value 
int M132_f(char *s) {
    debug("M132_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M133_f(const char *s)
// M133: Set PID I limit value 
int M133_f(char *s) {
    debug("M133_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M134_f(const char *s)
// M134: Write PID values to EEPROM 
int M134_f(char *s) {
    debug("M134_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M135_f(const char *s)
// M135: Set PID sample interval 
int M135_f(char *s) {
    debug("M135_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M136_f(const char *s)
// M136: Print PID settings to host 
int M136_f(char *s) {
    debug("M136_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M140_f(const char *s)
// M140: Set Bed Temperature (Fast) 
int M140_f(char *s) {
    debug("M140_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M141_f(const char *s)
// M141: Set Chamber Temperature (Fast) 
int M141_f(char *s) {
    debug("M141_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M142_f(const char *s)
// M142: Holding Pressure 
int M142_f(char *s) {
    debug("M142_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M143_f(const char *s)
// M143: Maximum heater temperature 
int M143_f(char *s) {
    debug("M143_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M144_f(const char *s)
// M144: Bed Standby 
int M144_f(char *s) {
    debug("M144_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M146_f(const char *s)
// M146: Set Chamber Humidity 
int M146_f(char *s) {
    debug("M146_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M149_f(const char *s)
// M149: Set temperature units 
int M149_f(char *s) {
    debug("M149_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M150_f(const char *s)
// M150: Set display color 
int M150_f(char *s) {
    debug("M150_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M155_f(const char *s)
// M155: Automatically send temperatures 
int M155_f(char *s) {
    debug("M155_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M160_f(const char *s)
// M160: Number of mixed materials 
int M160_f(char *s) {
    debug("M160_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M163_f(const char *s)
// M163: Set weight of mixed material 
int M163_f(char *s) {
    debug("M163_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M164_f(const char *s)
// M164: Store weights 
int M164_f(char *s) {
    debug("M164_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M165_f(const char *s)
// M165: Set multiple mix weights 
int M165_f(char *s) {
    debug("M165_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M190_f(const char *s)
// M190: Wait for bed temperature to reach target temp 
int M190_f(char *s) {
    debug("M190_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M191_f(const char *s)
// M191: Wait for chamber temperature to reach target temp 
int M191_f(char *s) {
    debug("M191_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M200_f(const char *s)
// M200: Set filament diameter 
int M200_f(char *s) {
    debug("M200_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M201_f(const char *s)
// M201: Set max printing acceleration 
int M201_f(char *s) {
    debug("M201_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M202_f(const char *s)
// M202: Set max travel acceleration 
int M202_f(char *s) {
    debug("M202_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M203_f(const char *s)
// M203: Set maximum feedrate 
int M203_f(char *s) {
    debug("M203_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M204_f(const char *s)
// M204: Set default acceleration 
int M204_f(char *s) {
    debug("M204_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M205_f(const char *s)
// M205: Advanced settings 
int M205_f(char *s) {
    debug("M205_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M206_f(const char *s)
// M206: Offset axes 
int M206_f(char *s) {
    debug("M206_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M207_f(const char *s)
// M207: Set retract length 
int M207_f(char *s) {
    debug("M207_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M208_f(const char *s)
// M208: Set unretract length 
int M208_f(char *s) {
    debug("M208_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M209_f(const char *s)
// M209: Enable automatic retract 
int M209_f(char *s) {
    debug("M209_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M210_f(const char *s)
// M210: Set homing feedrates 
int M210_f(char *s) {
    debug("M210_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M211_f(const char *s)
// M211: Disable/Enable software endstops 
int M211_f(char *s) {
    debug("M211_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M212_f(const char *s)
// M212: Set Bed Level Sensor Offset 
int M212_f(char *s) {
    debug("M212_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M218_f(const char *s)
// M218: Set Hotend Offset 
int M218_f(char *s) {
    debug("M218_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M220_f(const char *s)
// M220: Set speed factor override percentage 
int M220_f(char *s) {
    debug("M220_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M221_f(const char *s)
// M221: Set extrude factor override percentage 
int M221_f(char *s) {
    debug("M221_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M222_f(const char *s)
// M222: Set speed of fast XY moves 
int M222_f(char *s) {
    debug("M222_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M223_f(const char *s)
// M223: Set speed of fast Z moves 
int M223_f(char *s) {
    debug("M223_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M224_f(const char *s)
// M224: Enable extruder during fast moves 
int M224_f(char *s) {
    debug("M224_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M225_f(const char *s)
// M225: Disable on extruder during fast moves 
int M225_f(char *s) {
    debug("M225_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M226_f(const char *s)
// M226: Wait for pin state 
int M226_f(char *s) {
    debug("M226_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M227_f(const char *s)
// M227: Enable Automatic Reverse and Prime 
int M227_f(char *s) {
    debug("M227_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M228_f(const char *s)
// M228: Disable Automatic Reverse and Prime 
int M228_f(char *s) {
    debug("M228_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M229_f(const char *s)
// M229: Enable Automatic Reverse and Prime 
int M229_f(char *s) {
    debug("M229_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M230_f(const char *s)
// M230: Disable / Enable Wait for Temperature Change 
int M230_f(char *s) {
    debug("M230_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M231_f(const char *s)
// M231: Set OPS parameter 
int M231_f(char *s) {
    debug("M231_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M232_f(const char *s)
// M232: Read and reset max. advance values 
int M232_f(char *s) {
    debug("M232_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M240_f(const char *s)
// M240: Trigger camera 
int M240_f(char *s) {
    debug("M240_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M241_f(const char *s)
// M241: Stop conveyor belt motor / echo on 
int M241_f(char *s) {
    debug("M241_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M245_f(const char *s)
// M245: Start cooler 
int M245_f(char *s) {
    debug("M245_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M246_f(const char *s)
// M246: Stop cooler 
int M246_f(char *s) {
    debug("M246_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M250_f(const char *s)
// M250: Set LCD contrast 
int M250_f(char *s) {
    debug("M250_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M251_f(const char *s)
// M251: Measure Z steps from homing stop (Delta printers) 
int M251_f(char *s) {
    debug("M251_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M260_f(const char *s)
// M260: i2c Send Data 
int M260_f(char *s) {
    debug("M260_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M261_f(const char *s)
// M261: i2c Request Data 
int M261_f(char *s) {
    debug("M261_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M280_f(const char *s)
// M280: Set servo position 
int M280_f(char *s) {
    debug("M280_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M290_f(const char *s)
// M290: Baby stepping 
int M290_f(char *s) {
    debug("M290_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M300_f(const char *s)
// M300: Play beep sound 
int M300_f(char *s) {
    debug("M300_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M301_f(const char *s)
// M301: Set PID parameters 
int M301_f(char *s) {
    debug("M301_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M302_f(const char *s)
// M302: Allow cold extrudes 
int M302_f(char *s) {
    debug("M302_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M303_f(const char *s)
// M303: Run PID tuning 
int M303_f(char *s) {
    debug("M303_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M304_f(const char *s)
// M304: Set PID parameters - Bed 
int M304_f(char *s) {
    debug("M304_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M305_f(const char *s)
// M305: Set thermistor and ADC parameters 
int M305_f(char *s) {
    debug("M305_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M306_f(const char *s)
// M306: Set home offset calculated from toolhead position 
int M306_f(char *s) {
    debug("M306_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M307_f(const char *s)
// M307: Set or report heating process parameters 
int M307_f(char *s) {
    debug("M307_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M320_f(const char *s)
// M320: Activate autolevel (Repetier) 
int M320_f(char *s) {
    debug("M320_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M321_f(const char *s)
// M321: Deactivate autolevel (Repetier) 
int M321_f(char *s) {
    debug("M321_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M322_f(const char *s)
// M322: Reset autolevel matrix (Repetier) 
int M322_f(char *s) {
    debug("M322_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M323_f(const char *s)
// M323: Distortion correction on/off (Repetier) 
int M323_f(char *s) {
    debug("M323_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M340_f(const char *s)
// M340: Control the servos 
int M340_f(char *s) {
    debug("M340_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M350_f(const char *s)
// M350: Set microstepping mode 
int M350_f(char *s) {
    debug("M350_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M351_f(const char *s)
// M351: Toggle MS1 MS2 pins directly 
int M351_f(char *s) {
    debug("M351_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M355_f(const char *s)
// M355: Turn case lights on/off 
int M355_f(char *s) {
    debug("M355_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M360_f(const char *s)
// M360: Move to Theta 0 degree position 
int M360_f(char *s) {
    debug("M360_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M361_f(const char *s)
// M361: Move to Theta 90 degree position 
int M361_f(char *s) {
    debug("M361_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M362_f(const char *s)
// M362: Move to Psi 0 degree position 
int M362_f(char *s) {
    debug("M362_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M363_f(const char *s)
// M363: Move to Psi 90 degree position 
int M363_f(char *s) {
    debug("M363_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M364_f(const char *s)
// M364: Move to Psi + Theta 90 degree position 
int M364_f(char *s) {
    debug("M364_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M365_f(const char *s)
// M365: SCARA scaling factor 
int M365_f(char *s) {
    debug("M365_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M366_f(const char *s)
// M366: SCARA convert trim 
int M366_f(char *s) {
    debug("M366_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M370_f(const char *s)
// M370: Morgan manual bed level - clear map 
int M370_f(char *s) {
    debug("M370_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M371_f(const char *s)
// M371: Move to next calibration position 
int M371_f(char *s) {
    debug("M371_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M372_f(const char *s)
// M372: Record calibration value, and move to next position 
int M372_f(char *s) {
    debug("M372_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M373_f(const char *s)
// M373: End bed level calibration mode 
int M373_f(char *s) {
    debug("M373_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M374_f(const char *s)
// M374: Save calibration grid 
int M374_f(char *s) {
    debug("M374_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M375_f(const char *s)
// M375: Display matrix / Load Matrix 
int M375_f(char *s) {
    debug("M375_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M376_f(const char *s)
// M376: Set bed compensation taper 
int M376_f(char *s) {
    debug("M376_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M380_f(const char *s)
// M380: Activate solenoid 
int M380_f(char *s) {
    debug("M380_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M381_f(const char *s)
// M381: Disable all solenoids 
int M381_f(char *s) {
    debug("M381_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M400_f(const char *s)
// M400: Wait for current moves to finish 
int M400_f(char *s) {
    debug("M400_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M401_f(const char *s)
// M401: Lower z-probe 
int M401_f(char *s) {
    debug("M401_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M402_f(const char *s)
// M402: Raise z-probe 
int M402_f(char *s) {
    debug("M402_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M404_f(const char *s)
// M404: Filament width and nozzle diameter 
int M404_f(char *s) {
    debug("M404_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M405_f(const char *s)
// M405: Filament Sensor on 
int M405_f(char *s) {
    debug("M405_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M406_f(const char *s)
// M406: Filament Sensor off 
int M406_f(char *s) {
    debug("M406_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M407_f(const char *s)
// M407: Display filament diameter 
int M407_f(char *s) {
    debug("M407_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M408_f(const char *s)
// M408: Report JSON-style response 
int M408_f(char *s) {
    debug("M408_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M420_f(const char *s)
// M420: Leveling On/Off/Fade (Marlin) 
int M420_f(char *s) {
    debug("M420_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M421_f(const char *s)
// M421: Set a Mesh Bed Leveling Z coordinate 
int M421_f(char *s) {
    debug("M421_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M450_f(const char *s)
// M450: Report Printer Mode 
int M450_f(char *s) {
    debug("M450_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M451_f(const char *s)
// M451: Select FFF Printer Mode 
int M451_f(char *s) {
    debug("M451_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M452_f(const char *s)
// M452: Select Laser Printer Mode 
int M452_f(char *s) {
    debug("M452_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M453_f(const char *s)
// M453: Select CNC Printer Mode 
int M453_f(char *s) {
    debug("M453_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M460_f(const char *s)
// M460: Define temperature range for thermistor-controlled fan 
int M460_f(char *s) {
    debug("M460_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M500_f(const char *s)
// M500: Store parameters in EEPROM 
int M500_f(char *s) {
    debug("M500_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M501_f(const char *s)
// M501: Read parameters from EEPROM 
int M501_f(char *s) {
    debug("M501_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M502_f(const char *s)
// M502: Revert to the default "factory settings." 
int M502_f(char *s) {
    debug("M502_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M503_f(const char *s)
// M503: Print settings 
int M503_f(char *s) {
    debug("M503_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M530_f(const char *s)
// M530: Enable printing mode 
int M530_f(char *s) {
    debug("M530_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M531_f(const char *s)
// M531: Set print name 
int M531_f(char *s) {
    debug("M531_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M532_f(const char *s)
// M532: Set print progress 
int M532_f(char *s) {
    debug("M532_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M540_f(const char *s)
// M540: Enable/Disable "Stop SD Print on Endstop Hit" 
int M540_f(char *s) {
    debug("M540_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M550_f(const char *s)
// M550: Set Name 
int M550_f(char *s) {
    debug("M550_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M551_f(const char *s)
// M551: Set Password 
int M551_f(char *s) {
    debug("M551_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M552_f(const char *s)
// M552: Set IP address, enable/disable network interface 
int M552_f(char *s) {
    debug("M552_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M553_f(const char *s)
// M553: Set Netmask 
int M553_f(char *s) {
    debug("M553_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M554_f(const char *s)
// M554: Set Gateway 
int M554_f(char *s) {
    debug("M554_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M555_f(const char *s)
// M555: Set compatibility 
int M555_f(char *s) {
    debug("M555_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M556_f(const char *s)
// M556: Axis compensation 
int M556_f(char *s) {
    debug("M556_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M557_f(const char *s)
// M557: Set Z probe point or define probing grid 
int M557_f(char *s) {
    debug("M557_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M558_f(const char *s)
// M558: Set Z probe type 
int M558_f(char *s) {
    debug("M558_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M559_f(const char *s)
// M559: Upload configuration file 
int M559_f(char *s) {
    debug("M559_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M560_f(const char *s)
// M560: Upload web page file 
int M560_f(char *s) {
    debug("M560_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M561_f(const char *s)
// M561: Set Identity Transform 
int M561_f(char *s) {
    debug("M561_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M562_f(const char *s)
// M562: Reset temperature fault 
int M562_f(char *s) {
    debug("M562_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M563_f(const char *s)
// M563: Define or remove a tool 
int M563_f(char *s) {
    debug("M563_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M564_f(const char *s)
// M564: Limit axes 
int M564_f(char *s) {
    debug("M564_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M565_f(const char *s)
// M565: Set Z probe offset 
int M565_f(char *s) {
    debug("M565_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M566_f(const char *s)
// M566: Set allowable instantaneous speed change 
int M566_f(char *s) {
    debug("M566_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M567_f(const char *s)
// M567: Set tool mix ratios 
int M567_f(char *s) {
    debug("M567_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M568_f(const char *s)
// M568: Turn off/on tool mix ratios 
int M568_f(char *s) {
    debug("M568_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M569_f(const char *s)
// M569: Set axis direction and enable values 
int M569_f(char *s) {
    debug("M569_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M570_f(const char *s)
// M570: Configure heater fault detection 
int M570_f(char *s) {
    debug("M570_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M571_f(const char *s)
// M571: Set output on extrude 
int M571_f(char *s) {
    debug("M571_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M572_f(const char *s)
// M572: Set or report extruder pressure advance 
int M572_f(char *s) {
    debug("M572_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M573_f(const char *s)
// M573: Report heater PWM 
int M573_f(char *s) {
    debug("M573_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M574_f(const char *s)
// M574: Set endstop configuration 
int M574_f(char *s) {
    debug("M574_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M575_f(const char *s)
// M575: Set serial comms parameters 
int M575_f(char *s) {
    debug("M575_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M577_f(const char *s)
// M577: Wait until endstop is triggered 
int M577_f(char *s) {
    debug("M577_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M578_f(const char *s)
// M578: Fire inkjet bits 
int M578_f(char *s) {
    debug("M578_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M579_f(const char *s)
// M579: Scale Cartesian axes 
int M579_f(char *s) {
    debug("M579_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M580_f(const char *s)
// M580: Select Roland 
int M580_f(char *s) {
    debug("M580_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M581_f(const char *s)
// M581: Configure external trigger 
int M581_f(char *s) {
    debug("M581_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M582_f(const char *s)
// M582: Check external trigger 
int M582_f(char *s) {
    debug("M582_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M583_f(const char *s)
// M583: Wait for pin 
int M583_f(char *s) {
    debug("M583_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M584_f(const char *s)
// M584: Set drive mapping 
int M584_f(char *s) {
    debug("M584_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M585_f(const char *s)
// M585: Probe Tool 
int M585_f(char *s) {
    debug("M585_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M586_f(const char *s)
// M586: Configure network protocols 
int M586_f(char *s) {
    debug("M586_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M587_f(const char *s)
// M587: Store WiFi host network in list, or list stored networks 
int M587_f(char *s) {
    debug("M587_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M588_f(const char *s)
// M588: Forget WiFi host network 
int M588_f(char *s) {
    debug("M588_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M589_f(const char *s)
// M589: Configure access point parameters 
int M589_f(char *s) {
    debug("M589_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M590_f(const char *s)
// M590: Report current tool type and index 
int M590_f(char *s) {
    debug("M590_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M600_f(const char *s)
// M600: Filament change pause 
int M600_f(char *s) {
    debug("M600_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M605_f(const char *s)
// M605: Set dual x-carriage movement mode 
int M605_f(char *s) {
    debug("M605_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M665_f(const char *s)
// M665: Set delta configuration 
int M665_f(char *s) {
    debug("M665_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M666_f(const char *s)
// M666: Set delta endstop adjustment 
int M666_f(char *s) {
    debug("M666_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M667_f(const char *s)
// M667: Select CoreXY mode 
int M667_f(char *s) {
    debug("M667_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M668_f(const char *s)
// M668: Set Z-offset compensations polynomial 
int M668_f(char *s) {
    debug("M668_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M669_f(const char *s)
// M669: Set kinematics type and kinematics parameters 
int M669_f(char *s) {
    debug("M669_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M700_f(const char *s)
// M700: Level plate 
int M700_f(char *s) {
    debug("M700_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M701_f(const char *s)
// M701: Load filament 
int M701_f(char *s) {
    debug("M701_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M702_f(const char *s)
// M702: Unload filament 
int M702_f(char *s) {
    debug("M702_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M703_f(const char *s)
// M703: Get Board Type 
int M703_f(char *s) {
    debug("M703_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M710_f(const char *s)
// M710: Erase the EEPROM and reset the board 
int M710_f(char *s) {
    debug("M710_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M750_f(const char *s)
// M750: Enable 3D scanner extension 
int M750_f(char *s) {
    debug("M750_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M751_f(const char *s)
// M751: Register 3D scanner extension over USB 
int M751_f(char *s) {
    debug("M751_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M752_f(const char *s)
// M752: Start 3D scan 
int M752_f(char *s) {
    debug("M752_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M753_f(const char *s)
// M753: Cancel current 3D scanner action 
int M753_f(char *s) {
    debug("M753_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M754_f(const char *s)
// M754: Calibrate 3D scanner 
int M754_f(char *s) {
    debug("M754_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M755_f(const char *s)
// M755: Set alignment mode for 3D scanner 
int M755_f(char *s) {
    debug("M755_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M756_f(const char *s)
// M756: Shutdown 3D scanner 
int M756_f(char *s) {
    debug("M756_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M800_f(const char *s)
// M800: Fire start print procedure 
int M800_f(char *s) {
    debug("M800_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M801_f(const char *s)
// M801: Fire end print procedure 
int M801_f(char *s) {
    debug("M801_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M851_f(const char *s)
// M851: Set Z-Probe Offset 
int M851_f(char *s) {
    debug("M851_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M900_f(const char *s)
// M900: Set Linear Advance Scaling Factors 
int M900_f(char *s) {
    debug("M900_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M905_f(const char *s)
// M905: Set local date and time 
int M905_f(char *s) {
    debug("M905_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M906_f(const char *s)
// M906: Set motor currents 
int M906_f(char *s) {
    debug("M906_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M907_f(const char *s)
// M907: Set digital trimpot motor 
int M907_f(char *s) {
    debug("M907_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M908_f(const char *s)
// M908: Control digital trimpot directly 
int M908_f(char *s) {
    debug("M908_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M909_f(const char *s)
// M909: Set microstepping 
int M909_f(char *s) {
    debug("M909_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M910_f(const char *s)
// M910: Set decay mode 
int M910_f(char *s) {
    debug("M910_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M911_f(const char *s)
// M911: Set power monitor threshold voltages 
int M911_f(char *s) {
    debug("M911_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M912_f(const char *s)
// M912: Set electronics temperature monitor adjustment 
int M912_f(char *s) {
    debug("M912_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M913_f(const char *s)
// M913: Set motor percentage of normal current 
int M913_f(char *s) {
    debug("M913_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M928_f(const char *s)
// M928: Start SD logging 
int M928_f(char *s) {
    debug("M928_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M997_f(const char *s)
// M997: Perform in-application firmware update 
int M997_f(char *s) {
    debug("M997_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M998_f(const char *s)
// M998: Request resend of line 
int M998_f(char *s) {
    debug("M998_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M999_f(const char *s)
// M999: Restart after being stopped by error 
int M999_f(char *s) {
    debug("M999_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// G_f(const char *s)
// G: List all G-codes 
int G_f(char *s) {
    debug("G_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// M_f(const char *s)
// M: List all M-codes 
int M_f(char *s) {
    debug("M_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

// T_f(const char *s)
// T: Select Tool 
int T_f(char *s) {
    debug("T_f(const char *s) is not yet implemented!\n");
    debug("%s\n", s);
    return 1;
}

