//
// This file is generated by generate_gcode.py and should not be edited manually!
//
// gcode_functions.h
// generated on 2017-07-13
//

#ifndef GCODE_FUNCTIONS_H
#define GCODE_FUNCTIONS_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// N_f(char *s)
// N: Line number 
int N_f();

// G0_f(char *s)
// G0: Move 
int G0_f();

// G1_f(char *s)
// G1: Move 
int G1_f();

// G2_f(char *s)
// G2: Controlled Arc Move 
int G2_f();

// G3_f(char *s)
// G3: Controlled Arc Move 
int G3_f();

// G4_f(char *s)
// G4: Dwell 
int G4_f();

// G6_f(char *s)
// G6: Direct Stepper Move 
int G6_f();

// G10_f(char *s)
// G10: Retract 
int G10_f();

// G11_f(char *s)
// G11: Unretract 
int G11_f();

// G17_f(char *s)
// G17: Plane Selection (CNC specific) 
int G17_f();

// G18_f(char *s)
// G18: Plane Selection (CNC specific) 
int G18_f();

// G19_f(char *s)
// G19: Plane Selection (CNC specific) 
int G19_f();

// G20_f(char *s)
// G20: Set Units to Inches 
int G20_f();

// G21_f(char *s)
// G21: Set Units to Millimeters 
int G21_f();

// G22_f(char *s)
// G22: Firmware controlled Retract/Precharge 
int G22_f();

// G23_f(char *s)
// G23: Firmware controlled Retract/Precharge 
int G23_f();

// G26_f(char *s)
// G26: Mesh Validation Pattern 
int G26_f();

// G28_f(char *s)
// G28: Move to Origin (Home) 
int G28_f();

// G29_f(char *s)
// G29: Detailed Z-Probe 
int G29_f();

// G30_f(char *s)
// G30: Single Z-Probe 
int G30_f();

// G31_f(char *s)
// G31: Dock Z Probe sled 
int G31_f();

// G32_f(char *s)
// G32: Undock Z Probe sled 
int G32_f();

// G33_f(char *s)
// G33: Firmware dependent 
int G33_f();

// G38_f(char *s)
// G38: Straight Probe (CNC specific)
int G38_f();

// G40_f(char *s)
// G40: Compensation Off (CNC specific) 
int G40_f();

// G54_f(char *s)
// G54: Coordinate System Select (CNC specific) 
int G54_f();

// G55_f(char *s)
// G55: Coordinate System Select (CNC specific)
int G55_f();

// G56_f(char *s)
// G56: Coordinate System Select (CNC specific)
int G56_f();

// G57_f(char *s)
// G57: Coordinate System Select (CNC specific)
int G57_f();

// G58_f(char *s)
// G58: Coordinate System Select (CNC specific)
int G58_f();

// G59_f(char *s)
// G59: Coordinate System Select (CNC specific) 
int G59_f();

// G60_f(char *s)
// G60: save current position to slot 
int G60_f();

// G61_f(char *s)
// G61: Apply/restore saved coordinates to the active extruder. 
int G61_f();

// G80_f(char *s)
// G80: Cancel Canned Cycle (CNC specific) 
int G80_f();

// G90_f(char *s)
// G90: Set to Absolute Positioning 
int G90_f();

// G91_f(char *s)
// G91: Set to Relative Positioning 
int G91_f();

// G92_f(char *s)
// G92: Set Position 
int G92_f();

// G93_f(char *s)
// G93: Feed Rate Mode (Inverse Time Mode) (CNC specific) 
int G93_f();

// G94_f(char *s)
// G94: Feed Rate Mode (Units per Minute) (CNC specific) 
int G94_f();

// G100_f(char *s)
// G100: Calibrate floor or rod radius 
int G100_f();

// G130_f(char *s)
// G130: Set digital potentiometer value 
int G130_f();

// G131_f(char *s)
// G131: Remove offset 
int G131_f();

// G132_f(char *s)
// G132: Calibrate endstop offsets 
int G132_f();

// G133_f(char *s)
// G133: Measure steps to top 
int G133_f();

// G161_f(char *s)
// G161: Home axes to minimum 
int G161_f();

// G162_f(char *s)
// G162: Home axes to maximum 
int G162_f();

// M0_f(char *s)
// M0: Stop or Unconditional stop 
int M0_f();

// M1_f(char *s)
// M1: Sleep or Conditional stop 
int M1_f();

// M2_f(char *s)
// M2: Program End 
int M2_f();

// M3_f(char *s)
// M3: Spindle On, Clockwise  (CNC specific) 
int M3_f();

// M4_f(char *s)
// M4: Spindle On, Counter-Clockwise (CNC specific) 
int M4_f();

// M5_f(char *s)
// M5: Spindle Off (CNC specific) 
int M5_f();

// M6_f(char *s)
// M6: Tool change 
int M6_f();

// M7_f(char *s)
// M7: Mist Coolant On (CNC specific) 
int M7_f();

// M8_f(char *s)
// M8: Flood Coolant On (CNC specific) 
int M8_f();

// M9_f(char *s)
// M9: Coolant Off (CNC specific) 
int M9_f();

// M10_f(char *s)
// M10: Vacuum On (CNC specific) 
int M10_f();

// M11_f(char *s)
// M11: Vacuum Off (CNC specific) 
int M11_f();

// M17_f(char *s)
// M17: Enable/Power all stepper motors 
int M17_f();

// M18_f(char *s)
// M18: Disable all stepper motors 
int M18_f();

// M20_f(char *s)
// M20: List SD card 
int M20_f();

// M21_f(char *s)
// M21: Initialize SD card 
int M21_f();

// M22_f(char *s)
// M22: Release SD card 
int M22_f();

// M23_f(char *s)
// M23: Select SD file 
int M23_f();

// M24_f(char *s)
// M24: Start/resume SD print 
int M24_f();

// M25_f(char *s)
// M25: Pause SD print 
int M25_f();

// M26_f(char *s)
// M26: Set SD position 
int M26_f();

// M27_f(char *s)
// M27: Report SD print status 
int M27_f();

// M28_f(char *s)
// M28: Begin write to SD card 
int M28_f();

// M29_f(char *s)
// M29: Stop writing to SD card 
int M29_f();

// M30_f(char *s)
// M30: Delete a file on the SD card or SD card start to serial 
int M30_f();

// M32_f(char *s)
// M32: Select file and start SD print 
int M32_f();

// M33_f(char *s)
// M33: Get the long name for an SD card file or folder 
int M33_f();

// M34_f(char *s)
// M34: Set SD file sorting options 
int M34_f();

// M35_f(char *s)
// M35: Upload firmware NEXTION from SD 
int M35_f();

// M36_f(char *s)
// M36: Return file information 
int M36_f();

// M37_f(char *s)
// M37: Simulation mode 
int M37_f();

// M38_f(char *s)
// M38: Compute SHA1 hash of target file 
int M38_f();

// M40_f(char *s)
// M40: Eject 
int M40_f();

// M41_f(char *s)
// M41: Loop 
int M41_f();

// M42_f(char *s)
// M42: Switch I/O pin 
int M42_f();

// M43_f(char *s)
// M43: Pin report and debug 
int M43_f();

// M48_f(char *s)
// M48: Measure Z-Probe repeatability 
int M48_f();

// M70_f(char *s)
// M70: Display message 
int M70_f();

// M72_f(char *s)
// M72: Play a tone or song 
int M72_f();

// M73_f(char *s)
// M73: Set build percentage 
int M73_f();

// M80_f(char *s)
// M80: ATX Power On 
int M80_f();

// M81_f(char *s)
// M81: ATX Power Off 
int M81_f();

// M82_f(char *s)
// M82: Set extruder to absolute mode 
int M82_f();

// M83_f(char *s)
// M83: Set extruder to relative mode 
int M83_f();

// M84_f(char *s)
// M84: Stop idle hold 
int M84_f();

// M85_f(char *s)
// M85: Set inactivity shutdown timer 
int M85_f();

// M92_f(char *s)
// M92: Set axis_steps_per_unit 
int M92_f();

// M93_f(char *s)
// M93: Send axis_steps_per_unit 
int M93_f();

// M98_f(char *s)
// M98: Get axis_hysteresis_mm 
int M98_f();

// M99_f(char *s)
// M99: Set axis_hysteresis_mm 
int M99_f();

// M101_f(char *s)
// M101: Turn extruder 1 on (Forward), Undo Retraction 
int M101_f();

// M102_f(char *s)
// M102: Turn extruder 1 on (Reverse) 
int M102_f();

// M103_f(char *s)
// M103: Turn all extruders off, Extruder Retraction 
int M103_f();

// M104_f(char *s)
// M104: Set Extruder Temperature 
int M104_f();

// M105_f(char *s)
// M105: Get Extruder Temperature 
int M105_f();

// M106_f(char *s)
// M106: Fan On 
int M106_f();

// M107_f(char *s)
// M107: Fan Off 
int M107_f();

// M108_f(char *s)
// M108: Cancel Heating (Marlin) 
int M108_f();

// M109_f(char *s)
// M109: Set Extruder Temperature and Wait 
int M109_f();

// M110_f(char *s)
// M110: Set Current Line Number 
int M110_f();

// M111_f(char *s)
// M111: Set Debug Level 
int M111_f();

// M112_f(char *s)
// M112: Emergency Stop 
int M112_f();

// M113_f(char *s)
// M113: Set Extruder PWM 
int M113_f();

// M114_f(char *s)
// M114: Get Current Position 
int M114_f();

// M115_f(char *s)
// M115: Get Firmware Version and Capabilities 
int M115_f();

// M116_f(char *s)
// M116: Wait 
int M116_f();

// M117_f(char *s)
// M117: Display Message 
int M117_f();

// M118_f(char *s)
// M118: Negotiate Features 
int M118_f();

// M119_f(char *s)
// M119: Get Endstop Status 
int M119_f();

// M120_f(char *s)
// M120: Enable endstop detection 
int M120_f();

// M121_f(char *s)
// M121: Disable endstop detection 
int M121_f();

// M122_f(char *s)
// M122: Diagnose 
int M122_f();

// M123_f(char *s)
// M123: Tachometer value 
int M123_f();

// M124_f(char *s)
// M124: Immediate motor stop 
int M124_f();

// M126_f(char *s)
// M126: Open Valve 
int M126_f();

// M127_f(char *s)
// M127: Close Valve 
int M127_f();

// M128_f(char *s)
// M128: Extruder Pressure PWM 
int M128_f();

// M129_f(char *s)
// M129: Extruder pressure off 
int M129_f();

// M130_f(char *s)
// M130: Set PID P value 
int M130_f();

// M131_f(char *s)
// M131: Set PID I value 
int M131_f();

// M132_f(char *s)
// M132: Set PID D value 
int M132_f();

// M133_f(char *s)
// M133: Set PID I limit value 
int M133_f();

// M134_f(char *s)
// M134: Write PID values to EEPROM 
int M134_f();

// M135_f(char *s)
// M135: Set PID sample interval 
int M135_f();

// M136_f(char *s)
// M136: Print PID settings to host 
int M136_f();

// M140_f(char *s)
// M140: Set Bed Temperature (Fast) 
int M140_f();

// M141_f(char *s)
// M141: Set Chamber Temperature (Fast) 
int M141_f();

// M142_f(char *s)
// M142: Holding Pressure 
int M142_f();

// M143_f(char *s)
// M143: Maximum heater temperature 
int M143_f();

// M144_f(char *s)
// M144: Bed Standby 
int M144_f();

// M146_f(char *s)
// M146: Set Chamber Humidity 
int M146_f();

// M149_f(char *s)
// M149: Set temperature units 
int M149_f();

// M150_f(char *s)
// M150: Set display color 
int M150_f();

// M155_f(char *s)
// M155: Automatically send temperatures 
int M155_f();

// M160_f(char *s)
// M160: Number of mixed materials 
int M160_f();

// M163_f(char *s)
// M163: Set weight of mixed material 
int M163_f();

// M164_f(char *s)
// M164: Store weights 
int M164_f();

// M165_f(char *s)
// M165: Set multiple mix weights 
int M165_f();

// M190_f(char *s)
// M190: Wait for bed temperature to reach target temp 
int M190_f();

// M191_f(char *s)
// M191: Wait for chamber temperature to reach target temp 
int M191_f();

// M200_f(char *s)
// M200: Set filament diameter 
int M200_f();

// M201_f(char *s)
// M201: Set max printing acceleration 
int M201_f();

// M202_f(char *s)
// M202: Set max travel acceleration 
int M202_f();

// M203_f(char *s)
// M203: Set maximum feedrate 
int M203_f();

// M204_f(char *s)
// M204: Set default acceleration 
int M204_f();

// M205_f(char *s)
// M205: Advanced settings 
int M205_f();

// M206_f(char *s)
// M206: Offset axes 
int M206_f();

// M207_f(char *s)
// M207: Set retract length 
int M207_f();

// M208_f(char *s)
// M208: Set unretract length 
int M208_f();

// M209_f(char *s)
// M209: Enable automatic retract 
int M209_f();

// M210_f(char *s)
// M210: Set homing feedrates 
int M210_f();

// M211_f(char *s)
// M211: Disable/Enable software endstops 
int M211_f();

// M212_f(char *s)
// M212: Set Bed Level Sensor Offset 
int M212_f();

// M218_f(char *s)
// M218: Set Hotend Offset 
int M218_f();

// M220_f(char *s)
// M220: Set speed factor override percentage 
int M220_f();

// M221_f(char *s)
// M221: Set extrude factor override percentage 
int M221_f();

// M222_f(char *s)
// M222: Set speed of fast XY moves 
int M222_f();

// M223_f(char *s)
// M223: Set speed of fast Z moves 
int M223_f();

// M224_f(char *s)
// M224: Enable extruder during fast moves 
int M224_f();

// M225_f(char *s)
// M225: Disable on extruder during fast moves 
int M225_f();

// M226_f(char *s)
// M226: Wait for pin state 
int M226_f();

// M227_f(char *s)
// M227: Enable Automatic Reverse and Prime 
int M227_f();

// M228_f(char *s)
// M228: Disable Automatic Reverse and Prime 
int M228_f();

// M229_f(char *s)
// M229: Enable Automatic Reverse and Prime 
int M229_f();

// M230_f(char *s)
// M230: Disable / Enable Wait for Temperature Change 
int M230_f();

// M231_f(char *s)
// M231: Set OPS parameter 
int M231_f();

// M232_f(char *s)
// M232: Read and reset max. advance values 
int M232_f();

// M240_f(char *s)
// M240: Trigger camera 
int M240_f();

// M241_f(char *s)
// M241: Stop conveyor belt motor / echo on 
int M241_f();

// M245_f(char *s)
// M245: Start cooler 
int M245_f();

// M246_f(char *s)
// M246: Stop cooler 
int M246_f();

// M250_f(char *s)
// M250: Set LCD contrast 
int M250_f();

// M251_f(char *s)
// M251: Measure Z steps from homing stop (Delta printers) 
int M251_f();

// M260_f(char *s)
// M260: i2c Send Data 
int M260_f();

// M261_f(char *s)
// M261: i2c Request Data 
int M261_f();

// M280_f(char *s)
// M280: Set servo position 
int M280_f();

// M290_f(char *s)
// M290: Baby stepping 
int M290_f();

// M300_f(char *s)
// M300: Play beep sound 
int M300_f();

// M301_f(char *s)
// M301: Set PID parameters 
int M301_f();

// M302_f(char *s)
// M302: Allow cold extrudes 
int M302_f();

// M303_f(char *s)
// M303: Run PID tuning 
int M303_f();

// M304_f(char *s)
// M304: Set PID parameters - Bed 
int M304_f();

// M305_f(char *s)
// M305: Set thermistor and ADC parameters 
int M305_f();

// M306_f(char *s)
// M306: Set home offset calculated from toolhead position 
int M306_f();

// M307_f(char *s)
// M307: Set or report heating process parameters 
int M307_f();

// M320_f(char *s)
// M320: Activate autolevel (Repetier) 
int M320_f();

// M321_f(char *s)
// M321: Deactivate autolevel (Repetier) 
int M321_f();

// M322_f(char *s)
// M322: Reset autolevel matrix (Repetier) 
int M322_f();

// M323_f(char *s)
// M323: Distortion correction on/off (Repetier) 
int M323_f();

// M340_f(char *s)
// M340: Control the servos 
int M340_f();

// M350_f(char *s)
// M350: Set microstepping mode 
int M350_f();

// M351_f(char *s)
// M351: Toggle MS1 MS2 pins directly 
int M351_f();

// M355_f(char *s)
// M355: Turn case lights on/off 
int M355_f();

// M360_f(char *s)
// M360: Move to Theta 0 degree position 
int M360_f();

// M361_f(char *s)
// M361: Move to Theta 90 degree position 
int M361_f();

// M362_f(char *s)
// M362: Move to Psi 0 degree position 
int M362_f();

// M363_f(char *s)
// M363: Move to Psi 90 degree position 
int M363_f();

// M364_f(char *s)
// M364: Move to Psi + Theta 90 degree position 
int M364_f();

// M365_f(char *s)
// M365: SCARA scaling factor 
int M365_f();

// M366_f(char *s)
// M366: SCARA convert trim 
int M366_f();

// M370_f(char *s)
// M370: Morgan manual bed level - clear map 
int M370_f();

// M371_f(char *s)
// M371: Move to next calibration position 
int M371_f();

// M372_f(char *s)
// M372: Record calibration value, and move to next position 
int M372_f();

// M373_f(char *s)
// M373: End bed level calibration mode 
int M373_f();

// M374_f(char *s)
// M374: Save calibration grid 
int M374_f();

// M375_f(char *s)
// M375: Display matrix / Load Matrix 
int M375_f();

// M376_f(char *s)
// M376: Set bed compensation taper 
int M376_f();

// M380_f(char *s)
// M380: Activate solenoid 
int M380_f();

// M381_f(char *s)
// M381: Disable all solenoids 
int M381_f();

// M400_f(char *s)
// M400: Wait for current moves to finish 
int M400_f();

// M401_f(char *s)
// M401: Lower z-probe 
int M401_f();

// M402_f(char *s)
// M402: Raise z-probe 
int M402_f();

// M404_f(char *s)
// M404: Filament width and nozzle diameter 
int M404_f();

// M405_f(char *s)
// M405: Filament Sensor on 
int M405_f();

// M406_f(char *s)
// M406: Filament Sensor off 
int M406_f();

// M407_f(char *s)
// M407: Display filament diameter 
int M407_f();

// M408_f(char *s)
// M408: Report JSON-style response 
int M408_f();

// M420_f(char *s)
// M420: Leveling On/Off/Fade (Marlin) 
int M420_f();

// M421_f(char *s)
// M421: Set a Mesh Bed Leveling Z coordinate 
int M421_f();

// M450_f(char *s)
// M450: Report Printer Mode 
int M450_f();

// M451_f(char *s)
// M451: Select FFF Printer Mode 
int M451_f();

// M452_f(char *s)
// M452: Select Laser Printer Mode 
int M452_f();

// M453_f(char *s)
// M453: Select CNC Printer Mode 
int M453_f();

// M460_f(char *s)
// M460: Define temperature range for thermistor-controlled fan 
int M460_f();

// M500_f(char *s)
// M500: Store parameters in EEPROM 
int M500_f();

// M501_f(char *s)
// M501: Read parameters from EEPROM 
int M501_f();

// M502_f(char *s)
// M502: Revert to the default "factory settings." 
int M502_f();

// M503_f(char *s)
// M503: Print settings 
int M503_f();

// M530_f(char *s)
// M530: Enable printing mode 
int M530_f();

// M531_f(char *s)
// M531: Set print name 
int M531_f();

// M532_f(char *s)
// M532: Set print progress 
int M532_f();

// M540_f(char *s)
// M540: Enable/Disable "Stop SD Print on Endstop Hit" 
int M540_f();

// M550_f(char *s)
// M550: Set Name 
int M550_f();

// M551_f(char *s)
// M551: Set Password 
int M551_f();

// M552_f(char *s)
// M552: Set IP address, enable/disable network interface 
int M552_f();

// M553_f(char *s)
// M553: Set Netmask 
int M553_f();

// M554_f(char *s)
// M554: Set Gateway 
int M554_f();

// M555_f(char *s)
// M555: Set compatibility 
int M555_f();

// M556_f(char *s)
// M556: Axis compensation 
int M556_f();

// M557_f(char *s)
// M557: Set Z probe point or define probing grid 
int M557_f();

// M558_f(char *s)
// M558: Set Z probe type 
int M558_f();

// M559_f(char *s)
// M559: Upload configuration file 
int M559_f();

// M560_f(char *s)
// M560: Upload web page file 
int M560_f();

// M561_f(char *s)
// M561: Set Identity Transform 
int M561_f();

// M562_f(char *s)
// M562: Reset temperature fault 
int M562_f();

// M563_f(char *s)
// M563: Define or remove a tool 
int M563_f();

// M564_f(char *s)
// M564: Limit axes 
int M564_f();

// M565_f(char *s)
// M565: Set Z probe offset 
int M565_f();

// M566_f(char *s)
// M566: Set allowable instantaneous speed change 
int M566_f();

// M567_f(char *s)
// M567: Set tool mix ratios 
int M567_f();

// M568_f(char *s)
// M568: Turn off/on tool mix ratios 
int M568_f();

// M569_f(char *s)
// M569: Set axis direction and enable values 
int M569_f();

// M570_f(char *s)
// M570: Configure heater fault detection 
int M570_f();

// M571_f(char *s)
// M571: Set output on extrude 
int M571_f();

// M572_f(char *s)
// M572: Set or report extruder pressure advance 
int M572_f();

// M573_f(char *s)
// M573: Report heater PWM 
int M573_f();

// M574_f(char *s)
// M574: Set endstop configuration 
int M574_f();

// M575_f(char *s)
// M575: Set serial comms parameters 
int M575_f();

// M577_f(char *s)
// M577: Wait until endstop is triggered 
int M577_f();

// M578_f(char *s)
// M578: Fire inkjet bits 
int M578_f();

// M579_f(char *s)
// M579: Scale Cartesian axes 
int M579_f();

// M580_f(char *s)
// M580: Select Roland 
int M580_f();

// M581_f(char *s)
// M581: Configure external trigger 
int M581_f();

// M582_f(char *s)
// M582: Check external trigger 
int M582_f();

// M583_f(char *s)
// M583: Wait for pin 
int M583_f();

// M584_f(char *s)
// M584: Set drive mapping 
int M584_f();

// M585_f(char *s)
// M585: Probe Tool 
int M585_f();

// M586_f(char *s)
// M586: Configure network protocols 
int M586_f();

// M587_f(char *s)
// M587: Store WiFi host network in list, or list stored networks 
int M587_f();

// M588_f(char *s)
// M588: Forget WiFi host network 
int M588_f();

// M589_f(char *s)
// M589: Configure access point parameters 
int M589_f();

// M590_f(char *s)
// M590: Report current tool type and index 
int M590_f();

// M600_f(char *s)
// M600: Filament change pause 
int M600_f();

// M605_f(char *s)
// M605: Set dual x-carriage movement mode 
int M605_f();

// M665_f(char *s)
// M665: Set delta configuration 
int M665_f();

// M666_f(char *s)
// M666: Set delta endstop adjustment 
int M666_f();

// M667_f(char *s)
// M667: Select CoreXY mode 
int M667_f();

// M668_f(char *s)
// M668: Set Z-offset compensations polynomial 
int M668_f();

// M669_f(char *s)
// M669: Set kinematics type and kinematics parameters 
int M669_f();

// M700_f(char *s)
// M700: Level plate 
int M700_f();

// M701_f(char *s)
// M701: Load filament 
int M701_f();

// M702_f(char *s)
// M702: Unload filament 
int M702_f();

// M703_f(char *s)
// M703: Get Board Type 
int M703_f();

// M710_f(char *s)
// M710: Erase the EEPROM and reset the board 
int M710_f();

// M750_f(char *s)
// M750: Enable 3D scanner extension 
int M750_f();

// M751_f(char *s)
// M751: Register 3D scanner extension over USB 
int M751_f();

// M752_f(char *s)
// M752: Start 3D scan 
int M752_f();

// M753_f(char *s)
// M753: Cancel current 3D scanner action 
int M753_f();

// M754_f(char *s)
// M754: Calibrate 3D scanner 
int M754_f();

// M755_f(char *s)
// M755: Set alignment mode for 3D scanner 
int M755_f();

// M756_f(char *s)
// M756: Shutdown 3D scanner 
int M756_f();

// M800_f(char *s)
// M800: Fire start print procedure 
int M800_f();

// M801_f(char *s)
// M801: Fire end print procedure 
int M801_f();

// M851_f(char *s)
// M851: Set Z-Probe Offset 
int M851_f();

// M900_f(char *s)
// M900: Set Linear Advance Scaling Factors 
int M900_f();

// M905_f(char *s)
// M905: Set local date and time 
int M905_f();

// M906_f(char *s)
// M906: Set motor currents 
int M906_f();

// M907_f(char *s)
// M907: Set digital trimpot motor 
int M907_f();

// M908_f(char *s)
// M908: Control digital trimpot directly 
int M908_f();

// M909_f(char *s)
// M909: Set microstepping 
int M909_f();

// M910_f(char *s)
// M910: Set decay mode 
int M910_f();

// M911_f(char *s)
// M911: Set power monitor threshold voltages 
int M911_f();

// M912_f(char *s)
// M912: Set electronics temperature monitor adjustment 
int M912_f();

// M913_f(char *s)
// M913: Set motor percentage of normal current 
int M913_f();

// M928_f(char *s)
// M928: Start SD logging 
int M928_f();

// M997_f(char *s)
// M997: Perform in-application firmware update 
int M997_f();

// M998_f(char *s)
// M998: Request resend of line 
int M998_f();

// M999_f(char *s)
// M999: Restart after being stopped by error 
int M999_f();

// G_f(char *s)
// G: List all G-codes 
int G_f();

// M_f(char *s)
// M: List all M-codes 
int M_f();

// T_f(char *s)
// T: Select Tool 
int T_f();

#endif